spring:
  application:
    name:Books
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: qwerty12345
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
      format_sql: true
